name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        id: setup_go
        with:
          go-version: '1.13'
      - name: Cache go-modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
      - run: go mod download
      - run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.30.0
      - run: golangci-lint run  ./...
      - name: Run Go Releaser
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
